template: coreNormal
parent: 

style_group: {default}
  partial: {coreNormal}

style_group: {heading}
  partial: {coreNormal}

style_group: {body}
  partial: {coreNormal}

style_group: {front-matter}
  partial: {coreNormal}

style_group: {list}
  partial: {coreNormal}
  
style_group: {callout}
  partial: {coreNormal}
  
style_group: {caption}
  partial: {coreNormal}
  
style_group: {toc}
  partial: {coreNormal}
 
style_group: {header}
  partial: {coreNormal}

style_group: {footer}  
  partial: {coreNormal}

style_group: {other}
  partial: {coreNormal}
  
style_group: {character}
  partial: {coreNormal}
  
style_group: {table}
  partial: {coreNormal}